version: "3.3"

services:
  dagit:
    image: dagster/k8s-dagit-example
    container_name: dagit-container
    ports:
      - "8080:8080"
    volumes:
      - mount:/opt
    entrypoint: ["dagit", "-h", "0.0.0.0", "-p", "8080", "-w", "/opt/workspace.yaml"]

  daemon:
    image: dagster/k8s-dagit-example
    container_name: dagster-daemon
    volumes:
      - mount:/opt
    entrypoint: ["dagster-daemon", "run"]


volumes:
  mount: